# Generated by Django 6.0.3 on 2026-04-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
    ]
