# Generated by Django 6.0.3 on 2026-04-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_savedproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperty',
            name='ai_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='savedproperty',
            name='is_top_pick',
            field=models.BooleanField(default=False),
        ),
    ]
