# Generated by Django 6.0.3 on 2026-04-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_savedproperty_ai_score_savedproperty_is_top_pick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproperty',
            name='ai_score',
        ),
        migrations.RemoveField(
            model_name='savedproperty',
            name='is_top_pick',
        ),
        migrations.AddField(
            model_name='property',
            name='recommendation_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='top_pick',
            field=models.BooleanField(default=False),
        ),
    ]
