# Generated by Django 6.0.3 on 2026-04-03 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminotp_auditlog_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('EMAIL_VERIFICATION_SENT', 'Email Verification Sent'), ('EMAIL_VERIFIED', 'Email Verified'), ('EMAIL_VERIFICATION_FAILED', 'Email Verification Failed'), ('PROFILE_UPDATED', 'Profile Updated'), ('ADMIN_MFA_SENT', 'Admin MFA Sent'), ('ADMIN_MFA_SUCCESS', 'Admin MFA Success'), ('PROPERTY_CREATED', 'Property Created'), ('PROPERTY_UPDATED', 'Property Updated'), ('BOOKING_CREATED', 'Booking Created'), ('BOOKING_ACCEPTED', 'Booking Accepted'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_RESCHEDULED', 'Booking Rescheduled'), ('BOOKING_DELETED', 'Booking Deleted'), ('PROPERTY_SAVED', 'Property Saved'), ('PROPERTY_UNSAVED', 'Property Unsaved'), ('COMMENT_CREATED', 'Comment Created'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access')], max_length=50),
        ),
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
